### ISSUE TITLE
Repo for BuildBot buildmaster

### ISSUE THREAD

**Issue by codecurve** [cellml/libcellml-archived#10]
I'm using git to version the master.cfg edits.  I think it would be good if there was a "github.com/cellml/libcellml-build" repo that I could submit pull requests to etc.

The file contains buildslave passwords in plain text, so it will be necessary to blank those somehow.  Not sure what the security issues are if those leak, probably not serious, since others just use the default "pass" password anyway.

**Comment by nickerso** [comment]
Hi Randall, I think since this is an ABI specific aspect of the project it doesn't really belong under the CellML organisation. I have no real preference whether you just use your own repo directly Randall, or if you put it under the old ABI software lab organisation or somewhere else. But it would obviously make the most sense to follow whatever @hsorby and others have done with the existing buildbot projects.

I can't really comment on the security side of things, but putting plain text passwords in public github repositories seems like a bad idea to me.

**Comment by codecurve** [comment]
Easiest is using private GitHub repo on ABI-Software-Lab. Done.

**Comment by codecurve** [comment]
Plain-text passwords in master.cfg worked around, actual passwords changed from anything in version history, so made build repo public: https://github.com/ABI-Software-Laboratory/libcellml-build

**Comment by nickerso** [comment]
While that works for you Randall, it doesn't really help coordinate versions of the password file between users. Is there a reason why you don't just use an internal ABI subversion repo and keep all the information together and accessible to others at the ABI who maintain and use the build and test server?
