### ISSUE TITLE
Which license for new code?

### ISSUE THREAD

**Issue by codecurve** [cellml/libcellml-archived#2]
The ABI recently adopted MPL2 for OpenCMISS-Zinc, but this was strongly influenced by the previous use of MPL1.1 (see https://tracker.physiomeproject.org/show_bug.cgi?id=3558).

**Comment by nickerso** [comment]
I don't think we want to use MPL. I think something more along the lines of MIT or BSD would be best. This convinced me that BSD is best: http://www.astrobetter.com/the-whys-and-hows-of-licensing-scientific-code/

**Comment by agarny** [comment]
FWIW, and after having done my own personal research, I was going to release OpenCOR under the 3-clause BSD license, but then I was told (see https://tracker.physiomeproject.org/show_bug.cgi?id=3558) that it doesn't provide patent protection (should that ever be necessary) while Apache 2.0 does for example, in addition to being OSI approved, business friendly, having no copyleft and being compatible with major OSI licenses. So, in the end, I went for Apache 2.0 license rather than the 3-clause BSD one.

**Comment by jonc125** [comment]
Providing the licence chosen is open source and doesn't restrict use of the new library in both commercial and BSD-licensed code, then I don't mind what is used.  Chaste uses BSD now (we used to use LGPL but switched so as to gain an industry collaboration) so the licence needs to be compatible with that if we're to use it.

**Comment by nickerso** [comment]
We'll go with Apache 2.0 for now.
