### ISSUE TITLE
Use case "Create [very simple] model, serialise to XML (no maths)".

### ISSUE THREAD

**Issue by codecurve** [cellml/libcellml-archived#21]
Use case description:
Use libCellML to create a model, and serialise to XML.

This test code illustrates one way of doing this, from the caller's perspective:
https://github.com/codecurve/libcellml/blob/9a1e162fa2af0fc27808d10e0de8fc60b0899511/tests/XmlSerialisationTest.cpp#L17-L37

Note: 
For various reasons, depending on how you look at it, this issue deviates from the proposed libCellML development process.  Nevertheless, one of the main goals of submitting this issue now is that it will help illustrate some of the aspects of that process, for example, how BuildBot displays the results of builds and tests for the various revisions related to the corresponding pull request.  This was discussed at the libCellML meeting last week. Note that the above test code already has corresponding implementation code.  Build and test results are already visible under TravisCI, on a mock pull request created to illustrate this, see https://github.com/codecurve/libcellml/pull/3.

**Comment by agarny** [comment]
According to the specifications (see section 2.2.1), "CellML identifiers must consist of only alphanumeric characters and the underscore character ("_")". So, in your example, the name of the model, component and variable is not valid.

Otherwise, like others on the mailing list, I am not in favour of several levels of namespaces for libCellML (i.e. I would simply have `libcellml` rather than `libcellml::general` in this case). Also, has there been any kind of agreement when it comes to using namespaces in libCellML? Personally, I find that using `using namespace xxx;` often makes the code difficult to read and, therefore, to maintain.

**Comment by codecurve** [comment]
@agarny With regards to identifiers, I think the latest incantation of the rule was as given here: http://codecurve.github.io/cellml-core-spec/#idm179936091504, although I'm not sure of the level of consensus on that.  Nevertheless, either way, the example does not have a valid name as you correctly pointed out, but despite that, it is still suitable as a test for the very simple requirements of the use case, which don't require it to be valid, or to be validated.

**Comment by codecurve** [comment]
At the most recent libCellML meeting (12/2/15), it was decided that most of the code would be rolled-back, so this issue will be superseded in the future. This issue will be used just as a test of the process.

**Comment by codecurve** [comment]
@agarny Latest code had namespaces collapsed down to just `libcellml`.  I think `using` directives should be used judiciously and only when they aid legibility.

**Comment by codecurve** [comment]
Closing issue, discussion would move onto the pull request (cellml/libcellml#24), but in this case, not much discussion is expected, since it is really just a process drill.
